import express from 'express';
const router = express.Router();
import cityRouter from './city';
import locationRouter from './location';
import pointRouter from './point';
import tripRouter from './trip';
import authRouter from './auth';
import ticketRouter from './ticket';
import couponRouter from './coupon';
import couponManagementRouter from './couponManagement';
import paymentRouter from './payment';
import userRouter from './user';
import roleRouter from './role';
import partnerRouter from './partner';
import homeRouter from './home';
import staffRouter from './staff';
import routeRouter from './route';
import busRouteRouter from './busRoute';

router.use('/auth', authRouter);
router.use('/users', userRouter);
router.use('/roles', roleRouter);
router.use('/cities', cityRouter);
router.use('/locations', locationRouter);
router.use('/points', pointRouter);
router.use('/routes', routeRouter);
router.use('/bus-routes', busRouteRouter);
// router.use('/routes', routeTripRouter);
// router.use('/bus-companies', busCompanyRouter);
// router.use('/buses', busRouter);
// router.use('/types-bus', typeBusRouter);
router.use('/trips', tripRouter);
router.use('/tickets', ticketRouter);
router.use('/coupons', couponRouter);
router.use('/coupon-management', couponManagementRouter);
router.use('/payment', paymentRouter);
router.use('/partners', partnerRouter);
router.use('/home', homeRouter);
router.use('/company/staff', staffRouter);

export default router;