import express from 'express';
const router = express.Router();
import cityRouter from './city';
import locationRouter from './location';
import pointRouter from './point';
import tripRouter from './trip';
import authRouter from './auth';
import ticketRouter from './ticket';
import adminTicketRouter from './adminTicket';
import companyTicketRouter from './companyTicket';
import adminReviewRouter from './adminReview';
import companyReviewRouter from './companyReview';
import couponRouter from './coupon';
import couponManagementRouter from './couponManagement';
import paymentRouter from './payment';
import userRouter from './user';
import roleRouter from './role';
import partnerRouter from './partner';
import homeRouter from './home';
import staffRouter from './staff';
import routeRouter from './route';
import busRouteRouter from './busRoute';
import typeBusRouter from './typeBus';
import busRouter from './bus';
import companyTemplateRouter from './companyTemplate';
import companyTripRouter from './companyTrip';
import companyTripPointRouter from './companyTripPoint';

router.use('/auth', authRouter);
router.use('/users', userRouter);
router.use('/roles', roleRouter);
router.use('/cities', cityRouter);
router.use('/locations', locationRouter);
router.use('/points', pointRouter);
router.use('/routes', routeRouter);
router.use('/bus-routes', busRouteRouter);
router.use('/type-buses', typeBusRouter);
router.use('/buses', busRouter);
router.use('/templates', companyTemplateRouter);
router.use('/company-trips', companyTripRouter);
router.use('/company-trip-points', companyTripPointRouter);
router.use('/trips', tripRouter);
router.use('/tickets', ticketRouter);
router.use('/admin/tickets', adminTicketRouter);
router.use('/company-tickets', companyTicketRouter);
router.use('/admin-reviews', adminReviewRouter);
router.use('/company-reviews', companyReviewRouter);
router.use('/coupons', couponRouter);
router.use('/coupon-management', couponManagementRouter);
router.use('/payment', paymentRouter);
router.use('/partners', partnerRouter);
router.use('/home', homeRouter);
router.use('/company/staff', staffRouter);

export default router;